var path = require('path');
var webpack = require("webpack");
var HtmlWebpackPlugin = require('html-webpack-plugin');
var CopyWebpackPlugin = require('copy-webpack-plugin');
var CleanWebpackPlugin = require('clean-webpack-plugin');
var CssSourcemapPlugin = require('css-sourcemaps-webpack-plugin');

module.exports = function(appEnv) {
    var plugins = [
        new CleanWebpackPlugin(['build'], {
            root: __dirname + '/../',
            verbose: true
        }),
        new HtmlWebpackPlugin({
            template: path.resolve(__dirname + '/../app/index.html'),
            filename: 'index.html',
            inject: 'body',
            minify: {
                caseSensitive: true,
                collapseBooleanAttributes: true,
                collapseInlineTagWhitespace: false,
                collapseWhitespace: true,
                conservativeCollapse: false,
                decodeEntities: true,
                html5: true,
                includeAutoGeneratedTags: true,
                keepClosingSlash: true,
                minifyCSS: true,
                minifyJS: true,
                minifyURLs: ['data', 'javascript', 'mailto'],
                preserveLineBreaks: false,
                preventAttributesEscaping: false,
                processConditionalComments: false,
                processScripts: ['text/html'],
                removeAttributeQuotes: true,
                removeComments: true,
                removeEmptyAttributes: true,
                removeEmptyElements: false,
                removeOptionalTags: false,
                removeRedundantAttributes: false,
                removeScriptTypeAttributes: true,
                removeStyleLinkTypeAttributes: true,
                removeTagWhitespace: false,
                sortAttributes: true,
                sortClassName: true,
                useShortDoctype: true
            },
            chunksSortMode: 'dependency',
            hash: true
        }),
        new webpack.ProvidePlugin({
            $: "jquery",
            jQuery: "jquery",
            "window.jQuery": "jquery"
        }),
        new webpack.optimize.CommonsChunkPlugin({
            names: ['vendors','angularDependency','angular','bootstrap','jquery'],
            minChunks: Infinity,
            filename: '[name]-[hash][id].js'
        }),
        new webpack.DefinePlugin({
            'app': {
                'environment': JSON.stringify(appEnv)
            }
        })
    ];

    if (appEnv.environment == 'pro') {
        plugins.push(new webpack.optimize.UglifyJsPlugin({
            compress: {
                angular: true,
                warnings: false
            },
            comments: false,
            sourceMap: true
        }));
    } else {
        plugins.push(new CssSourcemapPlugin());
    }
    
    return plugins;
}